today

diff --git a/.github/workflows/main2.yml b/.github/workflows/main2.yml
--- a/.github/workflows/main2.yml
+++ b/.github/workflows/main2.yml
@@ -1,40 +1,72 @@
-# This is a basic workflow to help you get started with Actions
-
 name: credo_chocolatine
 
-# Controls when the workflow will run
 on:
-  # Triggers the workflow on push or pull request events but only for the main branch
+
   push:
     branches-ignore:
         - ga-ignore-
   pull_request:
     branches-ignore:
         - ga-ignore-
-    env:
-       MIRROR_URL: https://github.com/EpitechPromo2026/B-DOP-200-COT-2-1-chocolatine-olouwachegoun.badou.git
-       EXECUTABLES: pushwap
-  # Allows you to run this workflow manually from the Actions tab
+env:
+  MIRROR_URL: https://github.com/EpitechPromo2026/B-DOP-200-COT-2-1-chocolatine-olouwachegoun.badou.git
+  EXECUTABLES: pushwap
+
+
   workflow_dispatch:
 
-# A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
- check_repository_cleanliness:
-    # The type of runner that the job will run on
+  check_repository_cleanliness:
+  
     runs-on: ubuntu-latest
 
-    # Steps represent a sequence of tasks that will be executed as part of the job
     steps:
-      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access if
       - uses: actions/checkout@v3
 
       - name: Unwanted file detected
         run: |
-            var=$(find . -type f \( -name "*.o" -o -name "*~" -o -name "#*" -o -name "*.a" -o -name "*.so" -o -name "*.gcno" -o -name "*.gcda" -o -name "*.gcov" -o -name "tmp" \))
-            echo $var
+            my_variables=$(find . -type f \( -name "*.o" -o -name "*~" -o -name "#*" -o -name "*.a" -o -name "*.so" -o -name "*.gcno" -o -name "*.gcda" -o -name "*.gcov" -o -name "tmp" -o -name "*pain_au_chocolat*"\))
+            for each in $my_variable
+            do
+              echo "::error file=${each#./}, title=Unwanted file detected::$(each#./}"
+            done
+            if [[ -n $my_variables ]]
+            then
+             exit 1
+            else
+             echo "No unwanted file detected"
+             fi
+  check_program_compilation:
+    needs: check_repository_cleanliness
+    runs-on: ubuntu-latest
+    container:
+      image: epitechcontent/epitest-docker
 
+    steps:
+      - uses: actions/checkout@v3
+
+      -name: make
+       run: make
+       timeout-minutes: 2
+      -name: make clean
+       run: |
+          make clean
+          bin=$(find $EXECUTABLES)
+          
+          if [[ -n $bin ]]
+          then
+           echo "file is here"
+          else
+           exit 1
+          fi
+          if [[ -x $bin ]]
+          then
+           echo "file is executable"
+          else
+           exit 1
+          fi 
       # Runs a set of commands using the runners shell
-      - name: Run a multi-line script
-        run: |
-          echo Add other actions to build,
-          echo test, and deploy your project.
+      #- name: Run a multi-line script
+      #  run: |
+      #    echo Add other actions to build,
+      #    echo test, and deploy your project.
